mysql:
  ip: 172.39.8.44
  port: 3306
  schema: cdhr_platform_bmc_log
  username: root
  password: 111111x
info:
  name: spring-cloud fdsd starter
  version: 1.0
  publishtime: 2020-03-17
  description: testing
spring:
  datasource:
    url: jdbc:mysql://${mysql.ip}:${mysql.port}/${mysql.schema}?serverTimezone=Asia/Shanghai&useSSL=false
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Specify the DBMS
  jpa:
    database: MYSQL
    generate-ddl: true
    # Show or not log for each sql query
    show-sql: true

    # stripped before adding them to the dto manager)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false
    hibernate:
      ddl-auto: update
      # Naming strategy
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy