server:
  port: 1001
config-service:
  eureka:
    ip: 172.39.8.204
    port: 1000
spring:
  application:
    name: config-service
  #由于服务端加入spring securit的验证配置 需要加上这个配置信息来能够访问
#  security:
#    user:
#      name: user
#      password: 123456
  # 选择的同步工具
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/
        git:
          # git地址
          uri: https://github.com/zxwxiaohe1/properties.git
          # 搜索目录
          search-paths: properties
          # git仓库default-label默认值是master
          default-label: master
          clone-on-start: true
          force-pull: true
          username: 18428344227@163.com
          password: 111111xGithub
eureka:
  client:
    serviceUrl:
      #注册中心配置
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${config-service.eureka.ip}:${config-service.eureka.port}/eureka/
      defaultZone: http://${config-service.eureka.ip}:${config-service.eureka.port}/eureka/
  instance:
    prefer-ip-address: false

info:
  name: config service structure starter
  version: 1.0
  publishtime: 2020-03-17
  description: testing
